#!/usr/bin/env bash
#Bash script that displays:
# The content of the current directory
# In a list format

my_list=$(find . -maxdepth 1 | sed 's/^\.//' | sed 's/^\///' | sed 's/^[0-9]*-//')
for item in "${my_list[@]:1}";
do
  echo "$item"
done
